apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiclod.fullname" . }}-web
  labels:
    {{- include "aiclod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "aiclod.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.web.service.port }}
