apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiclod.fullname" . }}-api
  labels:
    {{- include "aiclod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "aiclod.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.api.service.port }}
